USE matheus;
CREATE SEQUENCE dbo.sequence_reset
    AS SMALLINT
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 32767
    CYCLE;

USE matheus;
CREATE TABLE SEND_COMMANDS (
	ID bigint IDENTITY(1,1) PRIMARY KEY,
	SEQUENCE_COMMAND SMALLINT DEFAULT NEXT VALUE FOR dbo.sequence_reset,
	IMEI bigint NOT NULL,
	COMMAND VARCHAR(1000),
	TRY_SEND TINYINT,
	RECEIVED_ACK BIT,	
)
	